### ISSUE TITLE
CURLOPT_SAFE_UPLOAD in HHVM

### ISSUE THREAD

**Issue by jimlind** [dg/twitter-php#45]
The use of CURLOPT_SAFE_UPLOAD introduced in v3.4 doesn't jive with my HHVM.
I've downgraded to v3.3 for now.

HipHop VM 3.4.2 (rel)
Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
Extension API: 20140829

Notice: Use of undefined constant CURLOPT_SAFE_UPLOAD - assumed 'CURLOPT_SAFE_UPLOAD' in ***/vendor/dg/twitter-php/src/Twitter.php

**Comment by brycied00d** [comment]
According to the PHP documentation, both the constant CURLOPT_SAFE_UPLOAD and the class CURLFile were introduced in PHP 5.5.0. Evidently, HHVM somehow has CURLFile (satisfying https://github.com/dg/twitter-php/blob/master/src/Twitter.php#L231) without having CURLOPT_SAFE_UPLOAD defined (used on https://github.com/dg/twitter-php/blob/master/src/Twitter.php#L255)
The use of CURLFile (and CURLOPT_SAFE_UPLOAD) was introduced by bfb628adfe4b9bd664447e73c300b40872a3b6fa between twitter-php v3.4 and v3.5. There is no reference to CURLOPT_SAFE_UPLOAD in 3.4.
