### ISSUE TITLE
Image - Using PHP Image Editor

### ISSUE THREAD

**Issue by tetrahydra** [dg/twitter-php#48]
Hello,

I tried to feed image generated by php, like this:
image.php?t=fb1&u=1&c=SP-1239&f=96509aa36f2fb275044508f2ad0c3802.jpg

But, I got this error:
Error: Cannot read the file imagefb.php?t=fb1&u=1&c=SP-1239&f=96509aa36f2fb275044508f2ad0c3802.jpg. Check if file exists on disk and check its permissions.

Photos need to be watermarked first for the website logo.

**Comment by kissifrot** [comment]
You will need to grab the generated file and put it in a temporary directory, then feed the retrieved file
